apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frpc-manager-data
  labels:
    app: frpc-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
